version: '2'
services:
  loomX:
    image: loomnetwork/loom
    network_mode: "host"
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "1"
